import { Inline, PBody, DataTable, SubHeading, VraagjeBox } from './SectionShared'

export default function Section() {
  return (
    <div className="space-y-5 text-slate-700 dark:text-slate-300 leading-relaxed">
      <SubHeading level={2}><Inline>{`Ontstaan van COPD: risicofactoren en oorzaken`}</Inline></SubHeading>
      <p className="leading-relaxed"><Inline>{`Het klassieke beeld is dat bij iemand met een bepaalde gevoeligheid roken een abnormale inflammatoire respons veroorzaakt. Daardoor raken de luchtwegen en/of alveoli beschadigd. Roken versnelt de normale leeftijdsgebonden afname van de longfunctie en leidt tot luchtwegobstructie en chronische klachten. Deze veranderingen zijn grotendeels irreversibel en kunnen tot exacerbaties leiden.`}</Inline></p>
      <p className="leading-relaxed"><Inline>{`Naast roken worden inmiddels meerdere andere oorzaken herkend. De gemene deler is dat veel van deze oorzaken grotendeels te voorkomen zijn.`}</Inline></p>
      <SubHeading><Inline>{`Tabel 2. Belangrijke oorzaken en risicocategorieën van COPD`}</Inline></SubHeading>
      <DataTable rows={[["Categorie", "Voorbeelden"], ["Erfelijke aanleg", "Genetische factoren, α1-antitrypsinedeficiëntie"], ["Afwijkende longontwikkeling", "Verminderde longgroei vanaf de jeugd"], ["Infecties", "Longinfecties in de jeugd, tuberculose, HIV"], ["Astma", "Astma op kinderleeftijd, slecht gecontroleerd astma"], ["Omgevingsfactoren", "Roken, passief roken, luchtvervuiling, biomassa, werkblootstelling"]]} />
      <SubHeading><Inline>{`Erfelijke aanleg en α1-antitrypsinedeficiëntie`}</Inline></SubHeading>
      <p className="leading-relaxed"><Inline>{`Rokerende familieleden van een patiënt met COPD hebben een verhoogd risico op COPD. Dat laat zien dat genetische factoren samen met omgevingsfactoren de gevoeligheid vergroten. De meeste genetische varianten dragen maar beperkt bij, maar het bekendste monogenetische voorbeeld is het SERPINA1-gen. Een mutatie hierin veroorzaakt α1-antitrypsinedeficiëntie.`}</Inline></p>
      <p className="leading-relaxed"><Inline>{`α1-antitrypsine is een eiwit dat in de lever wordt gemaakt. Het remt normaal proteasen in de alveoli en beschermt zo het longweefsel tegen afbraak. Bij een tekort ontstaat versnelde afbraak van de alveoli en dus emfyseem. Daarnaast kan het ook leverfibrose veroorzaken. α1-antitrypsinedeficiëntie komt voor bij 1-2% van de patiënten met COPD. De klachten lijken op die van “gewoon” COPD, maar patiënten presenteren zich vaak jonger en hebben vaak een snellere achteruitgang van de longfunctie.`}</Inline></p>
      <PBody text={`**Aandachtsvraag:** Waarom geeft een tekort aan α1-antitrypsine longschade?
**Mini-antwoord:** Omdat proteasen dan minder goed geremd worden en het longweefsel sneller wordt afgebroken.`} />
      <SubHeading><Inline>{`Afwijkende longontwikkeling`}</Inline></SubHeading>
      <p className="leading-relaxed"><Inline>{`De longontwikkeling begint al in utero en loopt door in de kindertijd, adolescentie en jongvolwassenheid. Daarna volgt normaal een langzame fysiologische afname van de longfunctie. Als de longontwikkeling al vroeg achterblijft, bijvoorbeeld door een lage start of een groeistoornis, kan iemand op jongvolwassen leeftijd al een lagere pieklongfunctie hebben. Als daar later nog een versnelde afname bovenop komt, ontstaat sneller COPD.`}</Inline></p>
      <SubHeading><Inline>{`Infecties`}</Inline></SubHeading>
      <p className="leading-relaxed"><Inline>{`Longinfecties zijn een belangrijke risicofactor, vooral naast roken en met name in lage-inkomenslanden. Onderste luchtweginfecties in de jeugd, vooral door RS-virus, worden geassocieerd met COPD op latere leeftijd. Frequente infecties in de eerste levensjaren hangen samen met afwijkingen in de longvasculatuur, airway remodeling, destructie van longparenchym en verminderde mucociliaire klaring en lokale afweer.`}</Inline></p>
      <p className="leading-relaxed"><Inline>{`Tuberculose kan ook COPD veroorzaken. De inflammatoire respons kan structurele schade aan de luchtwegen geven. Daarnaast kan endobronchiale tuberculose voorkomen.`}</Inline></p>
      <p className="leading-relaxed"><Inline>{`Bij HIV wordt een hoge prevalentie van COPD gezien, tot wel 23%. Ook is de afname van de longfunctie sneller. Leeftijd, BMI en CD4-getal zijn hierbij onafhankelijk geassocieerd met HIV-gerelateerde COPD.`}</Inline></p>
      <SubHeading><Inline>{`Astma en airway remodeling`}</Inline></SubHeading>
      <p className="leading-relaxed"><Inline>{`Astma op kinderleeftijd is een risicofactor voor COPD. Dat hangt waarschijnlijk deels samen met een verminderde longontwikkeling. Ook slecht gecontroleerd astma kan leiden tot *airway remodeling*: structurele veranderingen in de luchtweg die zorgen voor blijvende vernauwing. Daarbij zie je onder andere toename van glad spierweefsel, gobletcelhyperplasie, slijmproductie, angiogenese en subepitheliale fibrose.`}</Inline></p>
      <SubHeading><Inline>{`Omgevingsfactoren: roken, luchtvervuiling en werk`}</Inline></SubHeading>
      <p className="leading-relaxed"><Inline>{`Roken is de belangrijkste oorzaak van COPD. Daarbij gaat het niet alleen om actief roken, maar ook om passief roken, roken door de moeder tijdens de zwangerschap en vapen. In hoge-inkomenslanden is roken de oorzaak bij ongeveer 70% van de COPD-patiënten; in lage-inkomenslanden ligt dat lager, rond 30-40%. Ook waterpijp, sigaar en cannabis zijn risicofactoren.`}</Inline></p>
      <p className="leading-relaxed"><Inline>{`Rokers hebben vaker luchtwegklachten, een verminderde longfunctie, een grotere afname in FEV1 en een hogere COPD-gerelateerde mortaliteit dan niet-rokers. Een pakjaar betekent 20 sigaretten per dag gedurende 1 jaar.`}</Inline></p>
      <p className="leading-relaxed"><Inline>{`Passief roken veroorzaakt schade op vergelijkbare wijze als actief roken. Roken tijdens de zwangerschap kan leiden tot een lagere longfunctie bij geboorte en dus tot een lagere pieklongfunctie later. Mogelijk spelen ook epigenetische veranderingen bij de foetus een rol.`}</Inline></p>
      <p className="leading-relaxed"><Inline>{`Biomassa is een belangrijke bron van luchtverontreiniging binnenshuis. Wereldwijd gebruiken ongeveer 3 miljard mensen biomassa als brandstof voor verwarming en koken. Ook buitenluchtvervuiling en werkgerelateerde blootstelling aan dampen, gassen en stoffen, zoals in de bouw of bij pesticiden, dragen bij.`}</Inline></p>
    </div>
  )
}
