import { Inline, PBody, DataTable, SubHeading, VraagjeBox } from './SectionShared'

export default function Section() {
  return (
    <div className="space-y-5 text-slate-700 dark:text-slate-300 leading-relaxed">
      <SubHeading level={2}><Inline>{`Tabel 1. Voorbeelden van blootstellingen bij HP`}</Inline></SubHeading>
      <DataTable rows={[["Blootstelling", "Bron", "Voorbeelden van antigenen"], ["Vogels", "Duiven, parkieten, kippen, kanaries", "Eiwitten uit veren, dons, uitwerpselen, serum"], ["Schimmel", "Waterschade, optrekkend vocht", "Aspergillus, Cladosporium, Penicillium"], ["Landbouw", "Beschimmeld hooi of kuilvoer", "Saccharomyces, Aspergillus"], ["Airco / luchtbevochtiger / swamp cooler", "Verontreinigd water", "Thermoactinomyces, Aspergillus, Penicillium"], ["Hot tub", "Verontreinigd water", "Mycobacterium avium complex, Aspergillus fumigatus, Mycobacterium abscessus"], ["Metaalbewerking / machine operators", "Water-based metalworking fluid", "Mycobacterium avium complex, Mycobacterium immunogenum"], ["Summer-type HP", "Vochtige houten constructies", "Trichosporon"], ["Hout", "Beschimmeld hout zoals cedar, mahonie, den, redwood, spar, kurk", "Alternaria, Bacillus subtilis, Mucor, Rhizopus"], ["Isocyanaten", "Lijm, polyurethaanschuim, verf, plastic, harsen, lakken", "Isocyanate acid anhydrides"], ["Paddenstoelenwerkers", "Beschimmelde compost en paddenstoelen", "Shitake, bunashimeji, himeji, thermofiele actinomyceten"], ["Tuinieren / organisch afval", "Bodem, organisch afval", "Aspergillus fumigatus, Saccharopolyspora rectivirgula, thermofiele actinomyceten"], ["Blaasinstrumenten", "Saxofoon, trombone, doedelzak", "Mycobacterium chelonae/abscessus, Fusarium"], ["Salamiwerkers", "Schimmelstof", "Aspergillus, Cladosporium, Penicillium"], ["Kaaswassers", "Schimmelstof", "Penicillium"], ["Rietsuiker (bagassosis)", "Beschimmelde suikerrietvezels", "Thermoactinomyces sacchari"], ["Tandheelkundige producten", "Tandtechnici", "Methylacrylaten"], ["Lifeguards / zwembadmedewerkers", "Verontreinigde waterstralen en sprays", "Pseudomonas"], ["CPAP-apparaat", "Verontreinigd water", "Schimmels en fungi"]]} />
      <p className="leading-relaxed"><Inline>{`De blootstelling kan dus op het werk plaatsvinden, maar ook thuis of bij hobby’s. Denk bijvoorbeeld aan vogels, schimmel in huis, vochtige kelders of badkamers, dons in kussens of dekbedden, winterjassen met dons en zelfs blaasinstrumenten.`}</Inline></p>
      <PBody text={`**Aandachtsvraag:** moet je alleen aan werkblootstelling denken?
**Kort antwoord:** nee, ook hobby’s en blootstelling in huis kunnen HP veroorzaken.`} />
      <p className="leading-relaxed"><Inline>{`Ongeveer 12–28% van de gevallen is direct toe te schrijven aan werkblootstelling. De meest voorkomende werkgerelateerde oorzaak is landbouw. Ook blootstelling aan isocyanaten, bijvoorbeeld in metaalbewerkingsvloeistoffen, is de laatste decennia belangrijker geworden.`}</Inline></p>
    </div>
  )
}
