import { Inline, PBody, DataTable, SubHeading, VraagjeBox } from './SectionShared'

export default function Section() {
  return (
    <div className="space-y-5 text-slate-700 dark:text-slate-300 leading-relaxed">
      <SubHeading level={2}><Inline>{`Mijn buik groeit zo snel: obesitas en diabetes in de zwangerschap`}</Inline></SubHeading>
      <p className="leading-relaxed"><Inline>{`Bij een zwangere met een snel groeiende buik moet je denken aan obesitas en diabetes gravidarum. Eerst kijk je naar het BMI vóór de zwangerschap, of als dat onbekend is, bij de eerste controle. Een BMI van 18,5-24,0 kg/m² is normaal, 25,0-29,9 kg/m² is overgewicht, boven 30,0 kg/m² is obesitas en boven 35 kg/m² spreekt men van morbide obesitas.`}</Inline></p>
      <SubHeading><Inline>{`Tabel 3. BMI-classificatie`}</Inline></SubHeading>
      <DataTable rows={[["BMI", "Betekenis"], ["18,5-24,0 kg/m²", "Normaal gewicht"], ["25,0-29,9 kg/m²", "Overgewicht"], ["> 30,0 kg/m²", "Obesitas"], ["> 35 kg/m²", "Morbide obesitas"]]} />
      <p className="leading-relaxed"><Inline>{`Obesitas geeft een verhoogd risico op hypertensie, type 2-diabetes, hart- en vaatziekten en galstenen. In de zwangerschap is er daarnaast een verband met zwangerschapsdiabetes, zwangerschapshypertensie, pre-eclampsie, meerlingzwangerschappen, neurale buisdefecten, macrosomie van de foetus, vroeggeboorte, kunstverlossing, sectio caesarea, fluxus post partum, anesthesiegerelateerde complicaties en trombo-embolie.`}</Inline></p>
      <SubHeading><Inline>{`Waarom groeit de buik te snel?`}</Inline></SubHeading>
      <p className="leading-relaxed"><Inline>{`Bij een positieve dyscongruentie is de baarmoeder groter dan verwacht voor de zwangerschapsduur. De differentiaaldiagnose omvat macrosomie van de foetus, meerlingzwangerschap, molazwangerschap, structurele afwijkingen van de foetus, termijndiscussie, tweelingtransfusiesyndroom, partiële mola en polyhydramnion. Een termijndiscussie kan al vroeg worden uitgesloten als de termijn echografisch in het eerste trimester goed is vastgesteld. Ook een mola of meerlingzwangerschap zou dan meestal al eerder zichtbaar zijn geweest.`}</Inline></p>
      <p className="leading-relaxed"><Inline>{`Bij de beoordeling van een te snel groeiende buik zijn obesitas, een eerder kind van 4000 gram en een belaste familieanamnese voor diabetes aanwijzingen voor een gestoorde glucosetolerantie. Daardoor kan macrosomie ontstaan en kan de hoeveelheid vruchtwater toenemen. Toch moet je ook denken aan structurele afwijkingen van de foetus, zoals oesophagusatresie, waarbij de foetus niet goed kan slikken en er ruim vruchtwater ontstaat.`}</Inline></p>
      <SubHeading><Inline>{`Diagnostiek van zwangerschapsdiabetes`}</Inline></SubHeading>
      <p className="leading-relaxed"><Inline>{`Om zwangerschapsdiabetes te bevestigen, gebruik je laboratoriumonderzoek. Een nuchtere glucose wordt gemeten na minstens acht uur geen calorie-inname. HbA1c geeft een indruk van de glucosestofwisseling van de laatste maand. De orale glucosetolerantietest, of OGTT, meet de nuchtere glucose en de glucose 2 uur na inname van een drankje met 75 gram glucose.`}</Inline></p>
      <SubHeading><Inline>{`Tabel 4. Belangrijke glucosebepalingen`}</Inline></SubHeading>
      <DataTable rows={[["Onderzoek", "Betekenis"], ["Nuchtere glucose", "Glucose na minstens 8 uur geen calorie-inname"], ["HbA1c", "Glucosestofwisseling van de laatste maand"], ["OGTT", "Nuchtere waarde en 2 uur na 75 gram glucose"]]} />
      <SubHeading><Inline>{`Beleid bij diabetes gravidarum`}</Inline></SubHeading>
      <p className="leading-relaxed"><Inline>{`Als de OGTT gestoord is, wordt de patiënte eerst begeleid door een diëtist. Het doel is een goede verdeling van koolhydraten, zodat de glucosewaarden zo min mogelijk schommelen. Daarom wordt geadviseerd om 3 keer per dag te eten en 3 keer per dag een tussendoortje te nemen. De hoeveelheid voeding wordt aangepast aan het activiteitenniveau. Bij deze patiënte wordt de zorg in het ziekenhuis voortgezet, onder begeleiding van een gynaecoloog in een tweedelijns centrum.`}</Inline></p>
      <p className="leading-relaxed"><Inline>{`De multidisciplinaire zorg bestaat uit een diëtist, internist met diabetesverpleegkundige, gynaecoloog en later ook de kinderarts. De oogarts en neuroloog zijn hierbij niet standaard betrokken. Er worden regelmatig controles afgesproken, meestal tweewekelijks, met controle van de bloedsuikerwaarden en echografisch onderzoek om macrosomie en polyhydramnion vroeg op te sporen. De foetale buikomtrek kan daarbij al duidelijk voorlopen op de andere groeiparameters.`}</Inline></p>
      <PBody text={`**Aandachtsvraag:** Waarom wordt de foetale buikomtrek zo goed gevolgd?
**Mini-antwoord:** Omdat die vroeg kan laten zien dat er macrosomie ontstaat.`} />
      <SubHeading><Inline>{`Verloop en behandeling later in de zwangerschap`}</Inline></SubHeading>
      <p className="leading-relaxed"><Inline>{`Als de buik zeer gespannen aanvoelt, harde buiken ontstaan en de foetale delen niet meer goed te voelen zijn, kan opname nodig zijn voor observatie. De foetale conditie wordt dan bewaakt met dagelijkse CTG-controle. Ook wordt opnieuw echografisch gekeken naar vooral slikbewegingen en maagvulling. De bloedsuikerwaarden worden strenger bewaakt in overleg met de internist. Gestreefd wordt naar waarden tussen 3,0 en 7,0 mmol/l. Als de waarden herhaaldelijk boven 10,0 mmol/l liggen, komt insulinetherapie in beeld.`}</Inline></p>
      <SubHeading><Inline>{`Bevalling en neonatale zorg`}</Inline></SubHeading>
      <p className="leading-relaxed"><Inline>{`Bij extreme macrosomie kan de baring worden ingeleid. In de casus gebeurt dat met misoprostol. De geboorte kan bemoeilijkt zijn, vooral door de schouders, wat past bij schouderdystocie. De pasgeborene wordt daarna opgenomen voor bloedsuikercontroles op de neonatologie.`}</Inline></p>
      <SubHeading><Inline>{`Gevolgen van zwangerschapsdiabetes`}</Inline></SubHeading>
      <p className="leading-relaxed"><Inline>{`Tijdens de zwangerschap is het onderscheid tussen zwangerschapsdiabetes en een voor het eerst ontdekte diabetes mellitus niet altijd goed te maken. Als de glucosetolerantie 6 weken postpartum weer normaal is, was er achteraf sprake van zwangerschapsdiabetes. Veel vrouwen ontwikkelen later alsnog manifeste diabetes mellitus; dat gebeurt bij de meerderheid binnen 10 tot 15 jaar. Ook is er een driemaal grotere kans op het metabool syndroom, met hypertensie, obesitas en dyslipidemie. Daarom wordt jaarlijkse controle van de bloedglucose geadviseerd.`}</Inline></p>
      <p className="leading-relaxed"><Inline>{`De foetus krijgt bij diabetes meer glucose via de placenta. Daardoor gaat de foetus meer insuline maken. Insuline werkt als groeihormoon en stimuleert de omzetting van glucose in glycogeen en vet. Dat verklaart macrosomie. Daarnaast kan polyhydramnion ontstaan doordat de foetus meer urine produceert door het verhoogde glucoseaanbod. Na de geboorte stopt de glucoseaanvoer plotseling, maar het kind maakt nog steeds veel insuline. Daardoor kan hypoglykemie ontstaan, met risico op convulsies en hersenbeschadiging.`}</Inline></p>
      <SubHeading><Inline>{`Schouderdystocie en sectio`}</Inline></SubHeading>
      <p className="leading-relaxed"><Inline>{`Schouderdystocie is moeilijk te voorspellen. Ook het geboortegewicht antenataal nauwkeurig schatten is lastig. Zowel uitwendig onderzoek met de handgrepen van Leopold als echografische gewichtsinschatting zijn vooral laat in de zwangerschap en bij grote kinderen onbetrouwbaar; afwijkingen van ongeveer 20% zijn mogelijk. Een electieve sectio caesarea is daarom niet standaard aangewezen alleen uit angst voor schouderdystocie. Een keizersnede kan wel worden overwogen bij een geschat geboortegewicht boven 5000 gram zonder diabetes en boven 4500 gram bij diabetes. In de praktijk wordt een sectio vooral geadviseerd als er eerder een ernstige schouderdystocie was met neonatale morbiditeit en als in de huidige zwangerschap opnieuw zeer hoge geboortegewichten worden verwacht.`}</Inline></p>
    </div>
  )
}
