import { Inline, PBody, DataTable, SubHeading, VraagjeBox } from './SectionShared'

export default function Section() {
  return (
    <div className="space-y-5 text-slate-700 dark:text-slate-300 leading-relaxed">
      <SubHeading level={2}><Inline>{`Buikpijn in de zwangerschap`}</Inline></SubHeading>
      <p className="leading-relaxed"><Inline>{`Tijdens de zwangerschap verandert het lichaam van de vrouw sterk. Veel orgaansystemen passen zich aan om de groei van de foetus mogelijk te maken en om het lichaam voor te bereiden op de baring. Daardoor kan buikpijn in de zwangerschap lastig te beoordelen zijn. Soms hoort de klacht bij de zwangerschap zelf, maar het kan ook gaan om een aandoening die los van de zwangerschap bestaat. Het is daarom belangrijk om klachten goed te interpreteren en steeds te bedenken of er sprake is van een zwangerschapsaandoening of niet.`}</Inline></p>
      <SubHeading><Inline>{`Hoe beoordeel je buikpijn in de tweede helft van de zwangerschap?`}</Inline></SubHeading>
      <p className="leading-relaxed"><Inline>{`Bij buikpijn in de tweede helft van de zwangerschap kijk je breed. Je beoordeelt eerst hoe ziek de zwangere oogt en hoe zij zich gedraagt in relatie tot de pijn. Is er bijvoorbeeld een duidelijke bewegingsdrang tijdens pijnaanvallen, of juist weeënactiviteit? Daarna onderzoek je de uterus en de foetus: zijn er contracties, hoe is de rusttonus van de uterus, bewegen de foetale delen normaal en zijn de foetale harttonen hoorbaar met de doptone?`}</Inline></p>
      <p className="leading-relaxed"><Inline>{`Ook de plaats van de pijn is belangrijk. Zit de pijn in het epigastrio, in de bovenbuik, onderbuik of juist rechts onder? Is er rugpijn? Is er pijn bij diep inademen? Is er spierverzet? Straalt de pijn uit? Verder controleer je de bloeddruk, temperatuur en pols. Bloed- of vruchtwaterverlies moet je objectiveren, en zo nodig doe je een vaginaal toucher.`}</Inline></p>
      <SubHeading><Inline>{`Tabel 1. Belangrijke onderdelen van het lichamelijk onderzoek bij buikpijn in de zwangerschap`}</Inline></SubHeading>
      <DataTable rows={[["Onderdeel", "Waar let je op?"], ["Algemene indruk", "Zieke indruk, gedrag, bewegingsdrang"], ["Uterus en foetus", "Weeënactiviteit, rusttonus, kindsbewegingen, foetale harttonen"], ["Buikonderzoek", "Lokalisatie van pijn, rugpijn, pijn bij ademhalen, défense musculaire, uitstraling"], ["Vitale functies", "Bloeddruk, pols, temperatuur"], ["Verloskundige signalen", "Bloedverlies, vruchtwaterverlies, vaginaal toucher"]]} />
      <SubHeading><Inline>{`Differentiaaldiagnose bij buikpijn`}</Inline></SubHeading>
      <p className="leading-relaxed"><Inline>{`Bij buikpijn in de zwangerschap denk je aan meerdere mogelijke oorzaken. Urineweginfecties, zoals cystitis en zwangerschapshydronefrose, kunnen nog niet worden uitgesloten. Een abruptio placentae is een belangrijke diagnose om aan te denken, omdat dit acuut ernstig kan zijn. Dan is de uterus vaak plankhard en is er hevige buikpijn. Soms is er in het begin nog geen bloedverlies. Bij een partiële abruptio placentae kan de pijn wisselen, is de rusttonus van de uterus vaak verhoogd en is er vaak gering bloedverlies. De foetale conditie kan dan snel verslechteren.`}</Inline></p>
      <p className="leading-relaxed"><Inline>{`Pyelitis, cholecystitis en appendicitis worden minder waarschijnlijk als er geen koorts of verhoging is. Ook cholelithiasis of cholecystitis passen minder goed als de pijn niet scherp is bij inademen en er geen relatie is met maaltijden. Een uretersteen is minder waarschijnlijk als het beeld niet acuut is en er geen sterke bewegingsdrang is. Een torsie van een adnextumor is bij een niet-acuut beeld ook minder waarschijnlijk. Bij pre-eclampsie of het HELLP-syndroom klaagt de zwangere vaak over een strak bandgevoel boven in de buik. Toch moet je bij hoge bloeddruk, misselijkheid en verminderde eetlust altijd verder onderzoek doen voordat je deze diagnose uitsluit.`}</Inline></p>
      <PBody text={`**Aandachtsvraag:** Waarom is een abruptio placentae zo belangrijk om snel te herkennen?
**Mini-antwoord:** Omdat de uterus dan vaak plankhard is, de pijn hevig is en de foetale conditie snel kan verslechteren.`} />
      <SubHeading><Inline>{`Valkuilen bij onderzoek en diagnostiek`}</Inline></SubHeading>
      <p className="leading-relaxed"><Inline>{`Er zijn een paar dingen waar je in de zwangerschap rekening mee moet houden. Leukocyten zijn normaal al verhoogd, dus alleen een verhoogd aantal leukocyten zegt niet genoeg; een linksverschuiving is diagnostisch belangrijker. Door overrekking van de buikspieren kan défense musculaire in een vergevorderde zwangerschap moeilijk vast te stellen zijn. Appendicitis is in de zwangerschap lastiger te herkennen doordat de appendix atypisch kan liggen. Klachten van het HELLP-syndroom worden soms ten onrechte gezien als buikgriep.`}</Inline></p>
      <p className="leading-relaxed"><Inline>{`Aanvullend onderzoek kan bestaan uit laboratoriumonderzoek, beeldvorming en overige diagnostiek. Denk aan bloedonderzoek met onder andere Hb, Ht, leukocyten, trombocyten, lever- en nierfuncties, CRP, amylase, lipase en D-dimeer. Ook urineonderzoek is belangrijk: urinescreening, urinekweek en zo nodig bloedkweek. Voor beeldvorming kunnen echo van de urinewegen en echo van de zwangerschap zinvol zijn; soms wordt ook CT van het abdomen genoemd. Verder kunnen CTG, microbloedonderzoek van de foetus en vruchtwaterpunctie onderdeel zijn van de beoordeling.`}</Inline></p>
      <SubHeading><Inline>{`Tabel 2. Voorbeelden van aanvullend onderzoek bij buikpijn in de zwangerschap`}</Inline></SubHeading>
      <DataTable rows={[["Type onderzoek", "Voorbeelden"], ["Laboratorium", "Hb, Ht, leukocyten, trombocyten, ASAT, ALAT, LDH, CRP, amylase, lipase, D-dimeer, nierfunctie"], ["Urine", "Eiwit, nitriet, leukocyten, erytrocyten, urinekweek"], ["Beeldvorming", "Echo urinewegen, echo zwangerschap, CT abdomen"], ["Overig", "CTG, microbloedonderzoek foetus, vruchtwaterpunctie"]]} />
      <SubHeading><Inline>{`Urineweginfectie in de zwangerschap`}</Inline></SubHeading>
      <p className="leading-relaxed"><Inline>{`In de casus past uiteindelijk het beeld het best bij een urineweginfectie. Een negatieve nitriettest sluit cystitis namelijk niet uit. Die test kan fout-negatief zijn bij een lage pH, hoge vitamine C-concentraties of wanneer de verwekker nitraat niet omzet in nitriet. Daarom stel je bij een negatieve nitriettest de diagnose op basis van het urinesediment en de urinekweek. De urine moet als midstream worden afgenomen, omdat verontreiniging met plaveiselcellen het resultaat onbetrouwbaar maakt.`}</Inline></p>
      <p className="leading-relaxed"><Inline>{`Een urineweginfectie komt in de zwangerschap vaker voor dan daarbuiten. Bij 5 tot 7% van de zwangeren is er asymptomatische bacteriurie, en ongeveer 25% daarvan ontwikkelt een manifeste urineweginfectie. Recidiverende urineweginfecties zijn reden voor nader onderzoek. Preventieve adviezen zijn veel drinken, plassen bij aandrang en niet uitstellen, en plassen na coïtus.`}</Inline></p>
      <SubHeading><Inline>{`Behandeling van cystitis in de zwangerschap`}</Inline></SubHeading>
      <p className="leading-relaxed"><Inline>{`Bij cystitis in de zwangerschap heeft nitrofurantoïne gedurende 7 dagen of amoxicilline/clavulaanzuur gedurende 7 dagen de voorkeur. Nitrofurantoïne wordt niet kort voor of tijdens de bevalling toegepast vanwege het risico op hemolyse bij de pasgeborene. Als β-hemolytische streptokok groep B uit de urine wordt gekweekt, wijst dat op ernstige maternale kolonisatie. Dan kan naast behandeling van de cystitis ook intraveneuze antibioticaprofylaxe tijdens de baring nodig zijn om een GBS-infectie bij de neonaat te voorkomen.`}</Inline></p>
      <PBody text={`**Aandachtsvraag:** Waarom is GBS in de urine extra belangrijk?
**Mini-antwoord:** Omdat het wijst op ernstige kolonisatie van de moeder en gevolgen kan hebben voor de neonaat.`} />
      <SubHeading><Inline>{`Myomen en buikpijn`}</Inline></SubHeading>
      <p className="leading-relaxed"><Inline>{`Myomen geven in de zwangerschap meestal geen problemen. Soms veroorzaken ze buikklachten door circulatiestoornissen. De pijn zit dan continu op de plaats van het myoom en kan in intensiteit wisselen. Meestal is pijnstilling voldoende en nemen de klachten binnen enkele dagen af. Soms belemmert een groot myoom de indaling van het kind, waardoor een sectio nodig is. In de kraamperiode kan door involutie van de uterus de bloedcirculatie in het myoom worden afgesneden. Het myoom wordt dan ischemisch en veroorzaakt pijn en koorts.`}</Inline></p>
      <SubHeading><Inline>{`Als er geen duidelijke lichamelijke oorzaak wordt gevonden`}</Inline></SubHeading>
      <p className="leading-relaxed"><Inline>{`Als buikpijn of harde buiken steeds terugkomen zonder duidelijke lichamelijke verklaring, moet je ook denken aan andere onderliggende problematiek, zoals psychosociale klachten of mishandeling. Angst kan een rol spelen: angst voor een slechte afloop van de zwangerschap, voor afwijkingen bij de baby of voor de pijn van de bevalling. Bij een multipara kan ook een eerdere problematische zwangerschap of traumatische baring meespelen. Soms is de combinatie van alle taken in het leven simpelweg zwaar. Dan zijn verkenning van het probleem en een gesprek in een veilige omgeving belangrijk.`}</Inline></p>
    </div>
  )
}
